### ISSUE TITLE
Activation Type Won't Change

### ISSUE THREAD

**Issue by AquaLawng** [TheIllusiveC4/VeinMining#22] opened 2021-06-23 00:23 UTC
Fabric Minecraft 1.17

Holding the activation key, such as crouch, performs the opposite.

Mining without sneaking automatically veinmines
Mining while sneaking disables veinmines. 

veinmining.json5 as follows:
// Whether to activate vein mining by standing, crouching, or holding down the keybind
"activationState": "KEYBINDING",

Changing local settings using Mod Menu does nothing, not even sure it's compatible

**Comment by TheIllusiveC4** [comment] 2021-06-23 05:34
I cannot reproduce this, the activation key works correctly for me. Please provide your versions for Cloth Config and Mod Menu. In addition, make sure that you either leave and re-enter your world or execute the `/reload` command if making config changes while in a world/server.

**Comment by AquaLawng** [comment] 2021-06-23 11:19
I should also clarify that this issue is happening on a server I am running for my friends and me. I have the mod on both client and server side, not sure if that's correct. 

Cloth Config 5.0.34 (Client)
Mod Menu 2.0.2 (Client)

**Comment by TheIllusiveC4** [comment] 2021-06-23 17:47
Are you changing the configs client or server-side?

**Comment by AquaLawng** [comment] 2021-06-23 17:55
I have tried changing the config for just client side, just server side,
and both.

I have even tried a new world, new client instance, and new server config
file.

Same result.

Also, it functions correctly in a single player world.

**Comment by AquaLawng** [comment] 2021-06-23 23:22
I've done some more testing.

- Deleted the server config file to start fresh. 
- Using a tool with the vein mine chat on stone vein mines it.
- Edit server config file from "blacklist" to "whitelist"- Add "#c:ores" 
- Restart server
- Now, mining stone does not vein mine.
- Edit server config from "standing" to "keybinding"
- Restart server
- It still vein mines while standing, not when crouching
(I now realize it's not backwards, crouching disables vein mine because you are no longer standing)

**Comment by TheIllusiveC4** [comment] 2021-06-24 03:11
Just making sure, if you do all of that and change the CLIENT config from "STANDING" to "KEYBINDING", does it still not work?

**Comment by AquaLawng** [comment] 2021-06-24 10:21
Clientside was set to KEYBINDING through all of the above steps

**Comment by TheIllusiveC4** [comment] 2021-06-25 01:35
Okay I think I know what's wrong. The config isn't properly read client-side, which will cause the activation type to always stay the same because it's only checked client-side (so changing the configs server-side won't do anything either). It'll be fixed in the next update.

**Comment by AquaLawng** [comment] 2021-06-25 14:18
That's great to hear, looking forward to test it out. How is it supposed to work when used on a server? Is the server side config the default?

**Comment by TheIllusiveC4** [comment] 2021-06-26 07:59
Well, essentially, every other value is read from the server so everything else _should_ work server-side only. It's just the activation state that is read client-side that is affected.

**Closed as completed** 2021-06-27 07:20 UTC
Labels: type: bug
