### ISSUE TITLE
Configuration in mod setting doesn't work on Multiplayer

### ISSUE THREAD

**Issue by Kullich** [TheIllusiveC4/VeinMining#29] opened 2021-08-19 19:21 UTC
Hi,

I'm playing with friend on our private server and if i want to change configuration for veinming i can but  nothing happened, whatever i select it allways veinmine while i'm standing, want to hold keybind to veinmine otherwise don't want it. 

But for my friend work perfectly fine. 

We are playing on v35 lastest version. 

Here is my configuration.

```
["vein mining"]
	#Whether to activate vein mining by standing, crouching, or holding down the keybind
	#Allowed Values: STANDING, CROUCHING, KEYBINDING
	activationState = "KEYBINDING"

```

It worked in other versions but not this one

**Comment by TheIllusiveC4** [comment] 2021-08-19 19:43
> We are playing on v35 lastest version.

Latest version of what? Vein Mining only goes up to 0.12 on Forge. What is your Vein Mining version?

Also, which config file exactly are you changing?

**Comment by Kullich** [comment] 2021-08-19 19:49
Ah sorry mb i wrote version of modpack 😅 

yeah we are on version 0.12 and I’m changing only client config,  can’t see other config for veinmining probably I’m just blind

**Comment by TheIllusiveC4** [comment] 2021-08-19 20:01
And you're sure you're only changing the one on your own client right? Not any of the configs on the server?

**Comment by TheIllusiveC4** [comment] 2021-08-19 20:03
Also, try restarting your client when you make the change, re-check the client config for the correct value, and then loading up into your server again.

**Comment by Kullich** [comment] 2021-08-19 20:04
Yes i’m changing only client config. After changing I look to my client config and it changes and i don’t have access to config on server side

**Comment by TheIllusiveC4** [comment] 2021-08-19 20:12
Just making sure, does both the server and your client have the 0.12 version of Vein Mining installed?

**Comment by Kullich** [comment] 2021-08-19 20:15
Yes, my friend said both version are the same. For him it’s working perfectly fine.

**Comment by TheIllusiveC4** [comment] 2021-08-19 20:39
That's weird that it would be different between you two. Are you and your friend doing the exact same thing? He changed his client config as well to `KEYBINDING` and his works?

**Comment by Kullich** [comment] 2021-08-19 20:45
Ye it’s weird, he changed his client config to `KEYBINDING` and works only if he holding that keybind. But for me working every time When I mine something and  if I’m holding shift it will breaks only one block

**Comment by TheIllusiveC4** [comment] 2021-08-19 21:00
Is this server located remotely or is it on his physical computer?

**Comment by Kullich** [comment] 2021-08-19 21:09
Server is remotely located

**Comment by TheIllusiveC4** [comment] 2021-08-19 21:29
Hmm, very strange. Honestly, it sounds like you're doing _something_ incorrectly on your end because if the server is located remotely, then your friend would be under the exact same conditions as you are but he managed to get it working. However, I'm not sure what the problem is exactly because, as you've described it, it sounds like you're doing everything correctly.

Can you share your `veinmining-client.toml` file exactly as it is?

**Comment by Kullich** [comment] 2021-08-20 08:48
Can't upload it here but inside this file is only 
`
["vein mining"]
	#Whether to activate vein mining by standing, crouching, or holding down the keybind
	#Allowed Values: STANDING, CROUCHING, KEYBINDING
	activationState = "KEYBINDING"
`

And now i know where was the problem... i have 2 versions of that modpack after removing one work perfectly fine. I didn't think this would be a problem.

Anyway thanks for tryin' to help me best you can.

**Comment by TheIllusiveC4** [comment] 2021-08-20 19:40
Oh, okay, I'll close this issue then if it's working now.

**Closed as completed by TheIllusiveC4** 2021-08-20 19:40 UTC
Labels: type: bug
